[MODEL_TUNING]
log_to_neptune = True
path_to_udpipe_model = models/20180506.uk.mova-institute.udpipe
path_to_save_fine_tuned_model = models/fine-tuned-models
path_to_wsd_eval_dataset = local_datasets/wsd_loss_data_homonyms_problematic.csv

path_to_triplet_dataset = local_datasets/semi_supervised_2/triplets_semi_supervised.csv
; path_to_triplet_dataset = local_datasets/semi_supervised/semi_supervised_triplets_hard_mined_with_target_ids.csv
loss = triplet_loss
; loss = mnr_loss
pool_targets=True
use_both_poolings=False

; path_to_triplet_dataset = local_datasets/ntxent_dataset_1.csv
; loss = nt_xent_loss

; model_to_fine_tune = intfloat/multilingual-e5-large
; batch_size = 32
; num_batch_to_eval = 300


; model_to_fine_tune = models/fine-tuned-models/model_-134_0
model_to_fine_tune = sentence-transformers/paraphrase-multilingual-mpnet-base-v2
tokenizer_name = sentence-transformers/paraphrase-multilingual-mpnet-base-v2
batch_size = 104
num_batch_to_eval = 200

; set to 0 to unfreeze all layers
layers_to_unfreeze = 0
random_model_weights_reinitialization = False
number_of_layers_for_reinitialization = 3
learning_rate = 2e-6
apply_warmup = True
warmup_ratio = 0.1
num_epochs = 2
early_stopping = 15
enable_gpu_parallel = True
neptune_project_name=hellcaster/ConEfuV2
max_grad_norm=1.0
